source "http://rubygems.org"

gem "tlsmail"
gem "mail"
gem "sinatra", "1.0.0"
gem "rack", "1.1.0"
gem "exceptional"
gem "erector"
gem "dm-core"
gem "dm-migrations"
gem "dm-timestamps"
gem "dm-types"
gem "dm-observer"
gem "dm-aggregates"
gem "dm-validations"
gem "dm-postgres-adapter"
gem "delayed_job", "2.0.3"
    # :git => "git://github.com/collectiveidea/delayed_job.git"

group :development do
  gem "dm-sqlite-adapter"
  gem "rake"
  gem "rspec"
  gem "rack-test"
end
